"""Menu seed data — imported once when DB has no menu items."""

SEED_CATEGORIES = [
    {"id": "karhai", "label": "🍲 Karhai", "desc": "Rich, slow-cooked karahis made fresh every day", "folder": "karhai",
     "images": ["IMG_5499.JPG","IMG_5510.JPG","IMG_5511.JPG","IMG_5512.JPG","IMG_5513.WEBP"],
     "names": ["Chicken Karahi","Mutton Karahi","Beef Karahi","Handi Karahi","Butter Karahi"],
     "prices": [850, 1100, 950, 800, 900]},
    {"id": "burger", "label": "🍔 Burgers", "desc": "Juicy, stacked burgers — loaded with flavour", "folder": "burger",
     "images": ["IMG_5555.JPG","IMG_5556.JPG","IMG_5557.JPG","IMG_5558.JPG","IMG_5559.JPG","IMG_5560.JPG","IMG_5561.JPG","IMG_5562.JPG"],
     "names": ["Zinger Burger","Crispy Chicken Burger","Double Patty Burger","BBQ Burger","Spicy Burger","Cheese Burger","Club Burger","Special Burger"],
     "prices": [350, 320, 480, 400, 370, 380, 420, 450]},
    {"id": "pizza", "label": "🍕 Pizza", "desc": "Stone-baked pizzas with bold Pakistani twists", "folder": "pizza",
     "images": ["Chicken-Fajita-1.webp","Kababish Pizza.webp","chicken supreme.webp","creamy pizza.jpg","delight.png","images.jpg","kalzon.jpg","sicilian-meatballs.webp","tikka pizza.jpg"],
     "names": ["Chicken Fajita Pizza","Kababish Pizza","Chicken Supreme","Creamy Pizza","Delight Pizza","Margherita","Calzone","Sicilian Meatball","Tikka Pizza"],
     "prices": [650, 600, 700, 580, 620, 500, 680, 750, 630]},
    {"id": "tikka", "label": "🔥 Tikka", "desc": "Charcoal-grilled tikkas, smoky & tender", "folder": "tikka",
     "images": ["IMG_5526.JPG","IMG_5527.JPG","IMG_5528.JPG"],
     "names": ["Chicken Tikka","Seekh Tikka","Malai Tikka"], "prices": [500, 450, 550]},
    {"id": "boti", "label": "🍖 Boti", "desc": "Tender grilled boti pieces packed with spice", "folder": "boti",
     "images": ["IMG_5530.JPG","IMG_5531.JPG","IMG_5532.JPG","IMG_5533.JPG","IMG_5534.JPG","IMG_5535.JPG"],
     "names": ["Chicken Boti","Mutton Boti","Beef Boti","Reshmi Boti","Seekh Boti","Mixed Boti"],
     "prices": [400, 550, 500, 420, 380, 480]},
    {"id": "rolls", "label": "🌯 Rolls", "desc": "Hot, stuffed rolls — perfect street food bite", "folder": "rolls",
     "images": ["IMG_5507.JPG","IMG_5519.JPG","IMG_5520.JPG","IMG_5521.JPG","IMG_5522.JPG","IMG_5523.PNG","IMG_5524.JPG","IMG_5525.JPG"],
     "names": ["Chicken Roll","Seekh Roll","Beef Roll","Paratha Roll","Veggie Roll","Special Roll","BBQ Roll","Club Roll"],
     "prices": [180, 200, 220, 160, 150, 250, 230, 280]},
    {"id": "sandwiches", "label": "🥪 Sandwiches", "desc": "Fresh, loaded sandwiches toasted to perfection", "folder": "sandwiches",
     "images": ["IMG_5576.JPG","IMG_5577.JPG","IMG_5578.JPG"],
     "names": ["Club Sandwich","Chicken Sandwich","Toasted Sandwich"], "prices": [280, 250, 220]},
    {"id": "paratha", "label": "🫓 Paratha", "desc": "Crispy, buttery parathas — a desi breakfast staple", "folder": "paratha",
     "images": ["IMG_5515.JPG","IMG_5545.JPG","IMG_5546.JPG","IMG_5547.JPG","IMG_5548.JPG","IMG_5549.JPG","IMG_5550.JPG","IMG_5551.JPG","IMG_5552.JPG","IMG_5553.JPG","IMG_5554.JPG"],
     "names": ["Plain Paratha","Aloo Paratha","Egg Paratha","Beef Paratha","Chicken Paratha","Keema Paratha","Paneer Paratha","Butter Paratha","Mixed Paratha","Desi Paratha","Special Paratha"],
     "prices": [60, 120, 100, 180, 160, 200, 150, 80, 140, 90, 220]},
    {"id": "pasta", "label": "🍝 Pasta", "desc": "Creamy & spicy pastas with a Pakistani soul", "folder": "pasta",
     "images": ["IMG_5497.JPG","IMG_5498.JPG","IMG_5500.JPG"],
     "names": ["Chicken Pasta","Creamy Pasta","Spicy Pasta"], "prices": [350, 380, 360]},
    {"id": "fries", "label": "🍟 Fries", "desc": "Golden, crispy fries — plain or loaded", "folder": "fries",
     "images": ["IMG_5568.JPG","IMG_5569.JPG","IMG_5570.JPG","IMG_5571.JPG","IMG_5572.JPG"],
     "names": ["Plain Fries","Masala Fries","Loaded Fries","Cheese Fries","Spicy Fries"],
     "prices": [150, 180, 250, 220, 200]},
    {"id": "wings", "label": "🍗 Wings", "desc": "Crispy, saucy chicken wings — totally addictive", "folder": "wings",
     "images": ["IMG_5502.JPG","IMG_5503.JPG","IMG_5504.JPG"],
     "names": ["BBQ Wings","Buffalo Wings","Honey Garlic Wings"], "prices": [400, 420, 450]},
    {"id": "chai", "label": "☕ Chai", "desc": "The soul of every gathering — perfectly brewed", "folder": "chai",
     "images": ["IMG_5536.JPG","IMG_5537.PNG","IMG_5538.JPG","IMG_5539.JPG","IMG_5540.JPG","IMG_5541.JPG","IMG_5542.JPG","IMG_5543.JPG","IMG_5544.JPG"],
     "names": ["Doodh Patti","Kashmiri Chai","Karak Chai","Green Tea","Cardamom Chai","Ginger Chai","Masala Chai","Black Tea","Mint Tea"],
     "prices": [60, 100, 80, 70, 80, 80, 90, 50, 70]},
    {"id": "beverage", "label": "🥤 Beverages", "desc": "Cool, refreshing drinks for every meal", "folder": "beverage",
     "images": ["IMG_5583.JPG","IMG_5584.JPG","IMG_5585.JPG","IMG_5586.JPG","IMG_5587.JPG"],
     "names": ["Mango Shake","Cold Coffee","Lemonade","Rooh Afza","Soft Drink"],
     "prices": [180, 200, 120, 100, 80]},
    {"id": "soup", "label": "🍜 Soup", "desc": "Warm, hearty soups for every season", "folder": "soup",
     "images": ["IMG_5573.JPG","IMG_5574.JPG"],
     "names": ["Chicken Corn Soup","Hot & Sour Soup"], "prices": [200, 220]},
    {"id": "salad", "label": "🥗 Salad", "desc": "Fresh, crunchy salads — light & healthy", "folder": "salad",
     "images": ["IMG_5582.JPG"], "names": ["Garden Salad"], "prices": [150]},
    {"id": "kids-menu", "label": "🧒 Kids Menu", "desc": "Fun, tasty bites made just for little ones", "folder": "kids menu",
     "images": ["IMG_5563.JPG","IMG_5564.JPG","IMG_5565.JPG","IMG_5566.JPG","IMG_5567.JPG"],
     "names": ["Mini Burger","Nuggets","Kids Pasta","Mini Pizza","Kids Deal"],
     "prices": [200, 180, 220, 250, 350]},
    {"id": "side-items", "label": "🍱 Side Items", "desc": "Perfect accompaniments to your main meal", "folder": "side items",
     "images": ["IMG_5516.WEBP","IMG_5517.JPG","IMG_5579.JPG","IMG_5580.JPG","IMG_5581.JPG"],
     "names": ["Raita","Naan","Garlic Naan","Tandoori Roti","Salted Butter"],
     "prices": [60, 30, 50, 25, 40]},
]

# Default availability per category when seeding
CAT_DEFAULTS = {
    "chai": {"dine_in": True, "takeaway": True, "delivery": False},
    "burger": {"dine_in": False, "takeaway": True, "delivery": True},
    "pizza": {"dine_in": True, "takeaway": False, "delivery": True},
    "karhai": {"dine_in": True, "takeaway": True, "delivery": True},
}

DEFAULT_FLAGS = {"dine_in": True, "takeaway": True, "delivery": True}

# Variant pricing now lives in the DATABASE (was hardcoded in the frontend).
# Each variant: {"label": str, "price_offset": number added to base price}.
VARIANT_MAP = {
    "karhai": [{"label": "Half", "price_offset": 0}, {"label": "Full", "price_offset": 400}],
    "pasta":  [{"label": "Half", "price_offset": 0}, {"label": "Full", "price_offset": 150}],
    "pizza":  [{"label": "Small", "price_offset": 0}, {"label": "Medium", "price_offset": 150}, {"label": "Large", "price_offset": 300}],
    "tikka":  [{"label": "Leg", "price_offset": 0}, {"label": "Chest", "price_offset": 50}],
    "boti":   [{"label": "Single", "price_offset": 0}, {"label": "Full", "price_offset": 250}],
    "wings":  [{"label": "Leg", "price_offset": 0}, {"label": "Chest", "price_offset": 50}],
}
